version: '3'
services:
  php-environment:
    container_name: eSuperMarket-php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8080:80
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass@123
      MYSQL_DATABASE: eSuperMarket
    volumes:
      - ./db:/docker-entrypoint-initdb.d
